#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
device_dir="$(cd "${script_dir}/.." && pwd)"
font_dir="${device_dir}/boards/atk-dnesp32s3/fonts"
license_dir="${device_dir}/third_party/source-han-sans"
work_dir="$(mktemp -d -t voice-satellite-fonts.XXXXXX)"
trap 'rm -rf "${work_dir}"' EXIT

font_url="https://raw.githubusercontent.com/adobe-fonts/source-han-sans/release/SubsetOTF/CN/SourceHanSansCN-Regular.otf"
license_url="https://raw.githubusercontent.com/adobe-fonts/source-han-sans/release/LICENSE.txt"
font_file="${work_dir}/SourceHanSansCN-Regular.otf"
font_sha256="e2bc8a2e7f37474b774fff8db758681ece40bb6947a90d571bce9dd60671a8e4"

mkdir -p "${font_dir}" "${license_dir}"
curl --fail --location --retry 5 --retry-all-errors "${font_url}" --output "${font_file}"
printf '%s  %s\n' "${font_sha256}" "${font_file}" | shasum -a 256 --check
curl --fail --location --retry 5 --retry-all-errors "${license_url}" \
  --output "${license_dir}/LICENSE.txt"

npx --yes lv_font_conv@1.5.3 \
  --size 16 --bpp 2 --format lvgl \
  --font "${font_file}" \
  --range 0x20-0xFF,0x2000-0x206F,0x3000-0x301F,0x4E00-0x9FFF,0xFF01-0xFF5E \
  --no-kerning --lv-include lvgl.h --lv-font-name vs_font_cjk_16 \
  --output "${font_dir}/vs_font_cjk_16.c"

npx --yes lv_font_conv@1.5.3 \
  --size 22 --bpp 2 --format lvgl \
  --font "${font_file}" --range 0x20-0x7E,0x2026 \
  --symbols '启动中等待设备配置正在连接网络云端按住说话我在听识别转发完成失败重连' \
  --no-kerning --lv-include lvgl.h --lv-font-name vs_font_ui_22 \
  --output "${font_dir}/vs_font_ui_22.c"

for generated_font in "${font_dir}/vs_font_cjk_16.c" "${font_dir}/vs_font_ui_22.c"; do
  awk '
    index($0, " * Opts:") == 1 {
      print " * Generated by devices/esp32/tools/generate-fonts.sh"
      next
    }
    { print }
  ' "${generated_font}" >"${generated_font}.tmp"
  mv "${generated_font}.tmp" "${generated_font}"
done
